import {Themes} from "@varlet/ui";

export const darkTheme = Themes.toViewport({
    ...Themes.md3Dark,
    "--hsl-primary": "222, 100%, 84%",
    "--color-primary": "#000000",
    "--hsl-on-primary": "214, 100%, 21%",
    "--color-on-primary": "hsla(var(--hsl-on-primary), 1)",
    "--hsl-primary-container": "#31323e",
    "--color-primary-container": "#31323e",
    "--hsl-on-primary-container": "225, 100%, 92%",
    "--color-on-primary-container": "#31323e",
    "--hsl-info": "226, 29%, 81%",
    "--color-info": "hsla(var(--hsl-info), 1)",
    "--hsl-on-info": "223, 23%, 21%",
    "--color-on-info": "hsla(var(--hsl-on-info), 1)",
    "--hsl-info-container": "222, 17%, 30%",
    "--color-info-container": "hsla(var(--hsl-info-container), 1)",
    "--hsl-on-info-container": "226, 71%, 92%",
    "--color-on-info-container": "hsla(var(--hsl-on-info-container), 1)",
    "--hsl-warning": "298, 35%, 81%",
    "--color-warning": "hsla(var(--hsl-warning), 1)",
    "--hsl-on-warning": "293, 25%, 21%",
    "--color-on-warning": "hsla(var(--hsl-on-warning), 1)",
    "--hsl-warning-container": "294, 19%, 30%",
    "--color-warning-container": "hsla(var(--hsl-warning-container), 1)",
    "--hsl-on-warning-container": "298, 86%, 92%",
    "--color-on-warning-container": "hsla(var(--hsl-on-warning-container), 1)",
    "--hsl-danger": "6, 100%, 84%",
    "--color-danger": "hsla(var(--hsl-danger), 1)",
    "--hsl-on-danger": "357, 100%, 21%",
    "--color-on-danger": "hsla(var(--hsl-on-danger), 1)",
    "--hsl-danger-container": "356, 100%, 29%",
    "--color-danger-container": "hsla(var(--hsl-danger-container), 1)",
    "--hsl-on-danger-container": "6, 100%, 84%",
    "--color-on-danger-container": "hsla(var(--hsl-on-danger-container), 1)",
    "--color-body": "#36393e",
    "--color-text": "#FFFFFF",
    "--hsl-on-surface-variant": "230, 11%, 79%",
    "--color-on-surface-variant": "hsla(var(--hsl-on-surface-variant), 1)",
    "--hsl-outline": "229, 5%, 58%",
    "--color-outline": "hsla(var(--hsl-outline), 1)",
    "--hsl-inverse-surface": "255, 7%, 89%",
    "--color-inverse-surface": "hsla(var(--hsl-inverse-surface), 1)",
    "--table-thead-th-text-align": "center",
    "--table-tbody-tr-hover-background": "transparent",
    "--table-thead-th-text-color": "#000000",
    "--table-tbody-td-text-color": "#000000",
    "--date-picker-title-date-font-size": "25px",
    "--date-picker-title-date-height": "30px",
    "--date-picker-body-background-color": "transparent",
    "--day-picker-content-item-button-font-size": "14px",
    "--space-size-normal-y": "0px",
    "--color-surface-container-highest": "#31323e",
    "--card-filled-background": "#31323e",
})