import {Themes} from "@varlet/ui";

export const darkTheme = Themes.toViewport({
    ...Themes.md3Dark,
    "--hsl-primary": "213, 100%, 81%",
    "--color-primary": "hsla(var(--hsl-primary), 1)",
    "--hsl-on-primary": "206, 100%, 17%",
    "--color-on-primary": "hsla(var(--hsl-on-primary), 1)",
    "--hsl-primary-container": "205, 100%, 25%",
    "--color-primary-container": "hsla(var(--hsl-primary-container), 1)",
    "--hsl-on-primary-container": "215, 100%, 91%",
    "--color-on-primary-container": "hsla(var(--hsl-on-primary-container), 1)",
    "--hsl-info": "218, 31%, 80%",
    "--color-info": "hsla(var(--hsl-info), 1)",
    "--hsl-on-info": "213, 27%, 20%",
    "--color-on-info": "hsla(var(--hsl-on-info), 1)",
    "--hsl-info-container": "213, 20%, 29%",
    "--color-info-container": "hsla(var(--hsl-info-container), 1)",
    "--hsl-on-info-container": "218, 70%, 91%",
    "--color-on-info-container": "hsla(var(--hsl-on-info-container), 1)",
    "--hsl-warning": "279, 41%, 82%",
    "--color-warning": "hsla(var(--hsl-warning), 1)",
    "--hsl-on-warning": "275, 27%, 22%",
    "--color-on-warning": "hsla(var(--hsl-on-warning), 1)",
    "--hsl-warning-container": "276, 20%, 31%",
    "--color-warning-container": "hsla(var(--hsl-warning-container), 1)",
    "--hsl-on-warning-container": "281, 100%, 93%",
    "--color-on-warning-container": "hsla(var(--hsl-on-warning-container), 1)",
    "--hsl-danger": "6, 100%, 84%",
    "--color-danger": "hsla(var(--hsl-danger), 1)",
    "--hsl-on-danger": "357, 100%, 21%",
    "--color-on-danger": "hsla(var(--hsl-on-danger), 1)",
    "--hsl-danger-container": "356, 100%, 29%",
    "--color-danger-container": "hsla(var(--hsl-danger-container), 1)",
    "--hsl-on-danger-container": "6, 100%, 84%",
    "--color-on-danger-container": "hsla(var(--hsl-on-danger-container), 1)",
    "--hsl-body": "210, 7%, 11%",
    "--color-body": "hsla(var(--hsl-body), 1)",
    "--hsl-text": "240, 7%, 89%",
    "--color-text": "hsla(var(--hsl-text), 1)",
    "--hsl-on-surface-variant": "225, 11%, 79%",
    "--color-on-surface-variant": "hsla(var(--hsl-on-surface-variant), 1)",
    "--hsl-outline": "220, 6%, 58%",
    "--color-outline": "hsla(var(--hsl-outline), 1)",
    "--hsl-inverse-surface": "240, 7%, 89%",
    "--color-inverse-surface": "hsla(var(--hsl-inverse-surface), 1)",
    "--table-thead-th-text-align": "center",
    "--table-tbody-tr-hover-background": "transparent",
    "--table-thead-th-text-color": "#000000",
    "--table-tbody-td-text-color": "#000000",
    "--date-picker-title-date-font-size": "25px",
    "--date-picker-title-date-height": "30px",
    "--date-picker-body-background-color": "transparent",
    "--day-picker-content-item-button-font-size": "14px",
    "--space-size-normal-y": "0px",
    "--date-picker-body-height": "auto",
    "--date-picker-body-padding": "0 10px 0 10px",
    "--date-picker-header-padding": "5px"
})